name: jianwuguidang
description: "断舍离跨端APP，Flutter开发，纯本地CSV存储"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  csv: ^5.0.2
  path_provider: ^2.1.2
  uuid: ^4.4.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0      # 新增：文件选择器
  share_plus: ^9.0.0       # 新增：文件分享

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  android_settings:
    label: "简物归档"